from typing import overload
import numpy as np
from numpy.typing import ArrayLike, NDArray
__version__: str
class Matrix:
    @overload
    def __init__(self, array: ArrayLike) -> None: ...
    @overload
    def __init__(self, rows: int, cols: int, value: float = ...) -> None: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def T(self) -> Matrix: ...
    def numpy(self) -> NDArray: ...
    def copy(self) -> Matrix: ...
    def __getitem__(self, index: tuple[int, int]) -> float: ...
    def __setitem__(self, index: tuple[int, int], value: float) -> None: ...
    def __matmul__(self, other: Matrix) -> Matrix: ...
    def __add__(self, other: Matrix) -> Matrix: ...
    def __sub__(self, other: Matrix) -> Matrix: ...
    def __mul__(self, value: float) -> Matrix: ...
    def __rmul__(self, value: float) -> Matrix: ...
    def transpose(self) -> Matrix: ...
    def solve(self, b: Matrix) -> Matrix: ...
    def least_squares(self, b: Matrix) -> Matrix: ...
    def solve_jacobi(self, b: Matrix, max_iterations: int = ..., tolerance: float = ...) -> Matrix: ...
    def power(self, exponent: int) -> Matrix: ...
    def reciprocal(self) -> Matrix: ...
    def make_column_stochastic(self) -> None: ...
    def sum(self) -> float: ...
    def difference_norm(self, other: Matrix) -> float: ...
class MatrixFloat:
    @overload
    def __init__(self, array: ArrayLike) -> None: ...
    @overload
    def __init__(self, rows: int, cols: int, value: float = ...) -> None: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def T(self) -> MatrixFloat: ...
    def numpy(self) -> NDArray: ...
    def copy(self) -> MatrixFloat: ...
    def __getitem__(self, index: tuple[int, int]) -> float: ...
    def __setitem__(self, index: tuple[int, int], value: float) -> None: ...
    def __matmul__(self, other: MatrixFloat) -> MatrixFloat: ...
    def __add__(self, other: MatrixFloat) -> MatrixFloat: ...
    def __sub__(self, other: MatrixFloat) -> MatrixFloat: ...
    def __mul__(self, value: float) -> MatrixFloat: ...
    def __rmul__(self, value: float) -> MatrixFloat: ...
    def transpose(self) -> MatrixFloat: ...
    def solve(self, b: MatrixFloat) -> MatrixFloat: ...
    def least_squares(self, b: MatrixFloat) -> MatrixFloat: ...
    def solve_jacobi(self, b: MatrixFloat, max_iterations: int = ..., tolerance: float = ...) -> MatrixFloat: ...
    def power(self, exponent: int) -> MatrixFloat: ...
    def reciprocal(self) -> MatrixFloat: ...
    def make_column_stochastic(self) -> None: ...
    def sum(self) -> float: ...
    def difference_norm(self, other: MatrixFloat) -> float: ...
def matmul(a: ArrayLike, b: ArrayLike) -> NDArray: ...
def solve(a: ArrayLike, b: ArrayLike) -> NDArray: ...
def least_squares(a: ArrayLike, b: ArrayLike) -> NDArray: ...
def solve_jacobi(a: ArrayLike, b: ArrayLike, *, max_iterations: int = ..., tolerance: float = ...) -> NDArray: ...
def polyval(coefficients: ArrayLike, x: float) -> float: ...
